name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "mian" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions
      with:
        tf_actions_version: 0.14.8
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: "./environments"

    - name: 'Terraform Validate'
      uses: hashicorp/terraform-github-actions
      with:
        tf_actions_version: 0.14.8
        tf_actions_subcommand: 'validate'
        tf_actions_working_dir: "./environments"
        
    - name: 'Terraform Plan'
      uses: hashicorp/terraform-github-actions
      with:
        tf_actions_version: 0.14.8
        tf_actions_subcommand: 'plan'
        tf_actions_working_dir: "./environments"
